### ISSUE TITLE
Do you have the T5 model after pre-training? We don't have enough computational resources to pre-train T5

### ISSUE THREAD

**Issue by shaoyuyoung** [antonio-mastropaolo/ICSME2021-Completion#1]

**Comment by antonio-mastropaolo** [comment]
Hello, you can find the pre-trained model in the online appendix following this link:
(https://drive.google.com/drive/folders/1pQKhs3NG26tbc3oQlzD9ylPIW2o20Eqt?usp=sharing)

**Comment by shaoyuyoung** [comment]
thank you very much
