### ISSUE TITLE
hello,where can i  find the file "test.source" and 'test.target' in the N-grams/main.py

### ISSUE THREAD

**Issue by shaoyuyoung** [antonio-mastropaolo/ICSME2021-Completion#2]
In the source code(N-grams/main.py), I don't know what these two files mean, do you have these two files? thank you

**Comment by antonio-mastropaolo** [comment]
Hello, the files you are looking for can be created in the following way:

At the following link: https://drive.google.com/drive/folders/1oTgUk4PxXaUjbnI_-61LK20hLD3c_LpX?usp=sharing
you find two files: (i) _test_javadoc.tsv_ and (ii) _test_inside.tsv_.

The file **_test.source_** is given by the first column of test_javadoc and test_inside, which you extract and put in append one to the other, writing the results in a txt file (i.e, source.test). In other words, this file contains all the instances found in the first column of these two files.

As for the second file (i.e, test.target), you perform the same procedure, but in this case, you focus on the second column of both TSVs files (i.e, test_javadoc and test_inside). Finally, you write all those instances in **_test.target_**
