### ISSUE TITLE
hello,I have some questions about the metrics

### ISSUE THREAD

**Issue by shaoyuyoung** [antonio-mastropaolo/ICSME2021-Completion#3]
I would like to know how you can use the metrics in your paper (which include Perfect predictions, BLEU score and so on) to evaluate n-grams and t5. Do you have any code or functions for that? Thank you very much

**Comment by antonio-mastropaolo** [comment]
By following the README, you find everything you need.
For instance, what you're looking for is here: https://github.com/antonio-mastropaolo/ICSME2021-Completion/tree/main/Miscellaneous

Make sure to read the README first; that helps you navigate the repository in such a way that you can find everything you need.

**Comment by shaoyuyoung** [comment]
i'm sorry and thank you very much
