### ISSUE TITLE
hello,where can I find the file 'javadoc_train_ngram.txt' and 'inside_train_ngram.txt'

### ISSUE THREAD

**Issue by zijin235** [antonio-mastropaolo/ICSME2021-Completion#5]
In the code '/N-Grams/main.py',Line 258 and Line 259,there are two files  'javadoc_train_ngram.txt' and 'inside_train_ngram.txt'.But i can't  find these two files in your project.Do you have them?Thank you

**Comment by antonio-mastropaolo** [comment]
Hello, the material needed to replicate the experiments and how to set the environments is detailed in the readme of the replication package. What you are looking for is available here:  https://drive.google.com/drive/folders/1VX4YV6BNxKt1cElXQd_b4e0YAI6thBgM
