### ISSUE TITLE
How do you calculate Perfect predictions and Levenshtein distance

### ISSUE THREAD

**Issue by QTC4SO** [antonio-mastropaolo/ICSME2021-Completion#7]
Hi.
I have some problems with the calculation of Perfect predictions and Levenshtein distance.
When you calculate the Perfect prediction and Levenshtein distance on 5 tokens, how do you treat the comments in datasets whose masked tokens are less then 5?

**Comment by antonio-mastropaolo** [comment]
Hi,

Let me clarify your doubts.

Let's assume the model produces as output a recommendation featured by 10-word tokens. If the very first three tokens  (P0, P1, P2) match the first three tokens of the target (T0, T1, T2), then we have a Perfect-Prediction@3.
You can follow the same logic to compute perfect prediction featured by up to 15-word tokens.

Therefore, if we have a target featured by 4 tokens, we cannot compute PP and LD for more than these 4 tokens.
Thus, we compute PP@1, PP@2. PP@3 and PP@4. Same thing for the LD.


I hope this helps clarify your doubts.
